use charabia::Language;
use wasm_bindgen::prelude::*;

#[wasm_bindgen(js_name = Language)]
#[derive(Clone)]
pub enum WasmLanguage {
    Zho,
    Epo,
    Eng,
    Rus,
    Cmn,
    Spa,
    Por,
    Ita,
    Ben,
    Fra,
    Deu,
    Ukr,
    Kat,
    Ara,
    Hin,
    Jpn,
    Heb,
    Yid,
    Pol,
    Amh,
    Jav,
    Kor,
    Nob,
    Dan,
    Swe,
    Fin,
    Tur,
    Nld,
    Hun,
    Ces,
    Ell,
    Bul,
    Bel,
    Mar,
    Kan,
    Ron,
    Slv,
    Hrv,
    Srp,
    Mkd,
    Lit,
    Lav,
    Est,
    Tam,
    Vie,
    Urd,
    Tha,
    Guj,
    Uzb,
    Pan,
    Aze,
    Ind,
    Tel,
    Pes,
    Mal,
    Ori,
    Mya,
    Nep,
    Sin,
    Khm,
    Tuk,
    Aka,
    Zul,
    Sna,
    Afr,
    Lat,
    Slk,
    Cat,
    Tgl,
    Hye,
}

impl From<Language> for WasmLanguage {
    fn from(lang: Language) -> Self {
        match lang {
            Language::Zho => WasmLanguage::Zho,
            Language::Epo => WasmLanguage::Epo,
            Language::Eng => WasmLanguage::Eng,
            Language::Rus => WasmLanguage::Rus,
            Language::Cmn => WasmLanguage::Cmn,
            Language::Spa => WasmLanguage::Spa,
            Language::Por => WasmLanguage::Por,
            Language::Ita => WasmLanguage::Ita,
            Language::Ben => WasmLanguage::Ben,
            Language::Fra => WasmLanguage::Fra,
            Language::Deu => WasmLanguage::Deu,
            Language::Ukr => WasmLanguage::Ukr,
            Language::Kat => WasmLanguage::Kat,
            Language::Ara => WasmLanguage::Ara,
            Language::Hin => WasmLanguage::Hin,
            Language::Jpn => WasmLanguage::Jpn,
            Language::Heb => WasmLanguage::Heb,
            Language::Yid => WasmLanguage::Yid,
            Language::Pol => WasmLanguage::Pol,
            Language::Amh => WasmLanguage::Amh,
            Language::Jav => WasmLanguage::Jav,
            Language::Kor => WasmLanguage::Kor,
            Language::Nob => WasmLanguage::Nob,
            Language::Dan => WasmLanguage::Dan,
            Language::Swe => WasmLanguage::Swe,
            Language::Fin => WasmLanguage::Fin,
            Language::Tur => WasmLanguage::Tur,
            Language::Nld => WasmLanguage::Nld,
            Language::Hun => WasmLanguage::Hun,
            Language::Ces => WasmLanguage::Ces,
            Language::Ell => WasmLanguage::Ell,
            Language::Bul => WasmLanguage::Bul,
            Language::Bel => WasmLanguage::Bel,
            Language::Mar => WasmLanguage::Mar,
            Language::Kan => WasmLanguage::Kan,
            Language::Ron => WasmLanguage::Ron,
            Language::Slv => WasmLanguage::Slv,
            Language::Hrv => WasmLanguage::Hrv,
            Language::Srp => WasmLanguage::Srp,
            Language::Mkd => WasmLanguage::Mkd,
            Language::Lit => WasmLanguage::Lit,
            Language::Lav => WasmLanguage::Lav,
            Language::Est => WasmLanguage::Est,
            Language::Tam => WasmLanguage::Tam,
            Language::Vie => WasmLanguage::Vie,
            Language::Urd => WasmLanguage::Urd,
            Language::Tha => WasmLanguage::Tha,
            Language::Guj => WasmLanguage::Guj,
            Language::Uzb => WasmLanguage::Uzb,
            Language::Pan => WasmLanguage::Pan,
            Language::Aze => WasmLanguage::Aze,
            Language::Ind => WasmLanguage::Ind,
            Language::Tel => WasmLanguage::Tel,
            Language::Pes => WasmLanguage::Pes,
            Language::Mal => WasmLanguage::Mal,
            Language::Ori => WasmLanguage::Ori,
            Language::Mya => WasmLanguage::Mya,
            Language::Nep => WasmLanguage::Nep,
            Language::Sin => WasmLanguage::Sin,
            Language::Khm => WasmLanguage::Khm,
            Language::Tuk => WasmLanguage::Tuk,
            Language::Aka => WasmLanguage::Aka,
            Language::Zul => WasmLanguage::Zul,
            Language::Sna => WasmLanguage::Sna,
            Language::Afr => WasmLanguage::Afr,
            Language::Lat => WasmLanguage::Lat,
            Language::Slk => WasmLanguage::Slk,
            Language::Cat => WasmLanguage::Cat,
            Language::Tgl => WasmLanguage::Tgl,
            Language::Hye => WasmLanguage::Hye,
        }
    }
}
